name: Provision infra
description: Provision infra

inputs:
  environment:
    required: true
    description: environment

runs:
  using: composite
  steps:
    - name: Init
      shell: bash
      working-directory: ./infra
      run: |
        ./batect moto:init

    - name: Lint
      shell: bash
      working-directory: ./infra
      run: |
        ./batect lint

    - name: Plan
      shell: bash
      working-directory: ./infra
      run: |
        # ./batect aws:plan -- -var environment=${{ inputs.environment }}
        ./batect moto:plan
