name: Deployment

on:
  push:

jobs:
  build-api:
    uses: ./.github/workflows/build-golang.yml
    with:
      name: api
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  staging:
    needs:
      - build-api
    uses: ./.github/workflows/provision-infra.yml
    with:
      environment: staging
