name: Deployment

on:
  push:

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/build-golang
        name: Build
        with:
          name: api
          github-token: ${{ secrets.GITHUB_TOKEN }}

  provision-staging-infra:
    name: Provision staging infra
    runs-on: ubuntu-latest
    needs:
      - build-api
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/provision-infra
        name: Provision infra
        with:
          environment: staging
