on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  provision-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init
        shell: bash
        working-directory: ./infra
        run: |
          ./batect moto:init

      - name: Lint
        shell: bash
        working-directory: ./infra
        run: |
          ./batect lint

      - name: Plan
        shell: bash
        working-directory: ./infra
        run: |
          # ./batect aws:plan -- -var environment=${{ inputs.environment }}
          ./batect moto:plan
